psychquest:
    password-hashing-secret: important-to-be-changed-at-production-important-to-be-changed-at-production
    # Token is valid 24 hours
    jwt-signing-secret: important-to-be-changed-at-production-important-to-be-changed-at-production
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000
